# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MatchingService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  pod 'Alamofire', '~> 4.8.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Toast-Swift', '~> 5.0.0'

  # Pods for MatchingService

end
