# Uncomment the next line to define a global platform for your project
platform :ios, '13.3'

target 'MatchingService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  pod 'Alamofire', '~> 4.8.0'
  pod 'AlamofireObjectMapper', '~> 5.2.0'
  pod 'Toast-Swift', '~> 5.0.0'
  pod 'ObjectMapper', '~> 3.4'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database' 
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  # Pods for MatchingService

end
