# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'MatchingService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  pod 'Alamofire', '~> 4.8.0'
  pod 'AlamofireObjectMapper', '~> 5.2.0'

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'

  pod 'Toast-Swift', '~> 5.0.0'
  pod 'ObjectMapper', '~> 3.4'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  # Optionally, include the Swift extensions if you're using Swift.
  pod 'FirebaseFirestoreSwift'

  # Pods for MatchingService

end
